# Source: sparkoperator/templates/spark-operator-rbac.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: sparkoperator-crb
  labels:
    app.kubernetes.io/name: sparkoperator
    helm.sh/chart: sparkoperator-0.8.6
    app.kubernetes.io/instance: sparkoperator
    app.kubernetes.io/managed-by: Helm
subjects:
  - kind: ServiceAccount
    name: sparkoperator
    namespace: default
roleRef:
  kind: ClusterRole
  name: sparkoperator-cr
  apiGroup: rbac.authorization.k8s.io
---
