# Source: sparkoperator/templates/spark-operator-serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: sparkoperator
  namespace: default
  labels:
    app.kubernetes.io/name: sparkoperator
    helm.sh/chart: sparkoperator-0.8.6
    app.kubernetes.io/instance: sparkoperator
    app.kubernetes.io/managed-by: Helm
---
