# Source: neo4j/templates/serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: neo4j
  labels:
    app.kubernetes.io/name: neo4j
    helm.sh/chart: neo4j-0.3.1
    app.kubernetes.io/instance: neo4j
    app.kubernetes.io/version: "0.0.1"
    app.kubernetes.io/managed-by: Helm
---
