# Source: fluentd/templates/deployment.yaml
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: fluentd
  labels:
    app: fluentd
    chart: fluentd-0.2.1
    release: fluentd
    heritage: Helm
spec:
  replicas: 
  selector:
    matchLabels:
      app: fluentd
      release: fluentd
  template:
    metadata:
      labels:
        app: fluentd
        release: fluentd
    spec:
      containers:
      - name: fluentd
        image: "gcr.io/google-containers/fluentd-elasticsearch:v2.3.1"
        imagePullPolicy: IfNotPresent
        env:
          - name: OUTPUT_HOST
            value: "elasticsearch-client.default.svc.cluster.local"
          - name: OUTPUT_PORT
            value: "9200"
          - name: OUTPUT_BUFFER_CHUNK_LIMIT
            value: "2M"
          - name: OUTPUT_BUFFER_QUEUE_LIMIT
            value: "8"
        resources:
            {}
        ports:
          - name: monitor-agent
            containerPort: 24220
            protocol: TCP
          - name: http-input
            containerPort: 9880
            protocol: TCP
        livenessProbe:
          httpGet:
            # Use percent encoding for query param.
            # The value is {"log": "health check"}.
            # the endpoint itself results in a new fluentd
            # tag 'fluentd.pod-healthcheck'
            path: /fluentd.pod.healthcheck?json=%7B%22log%22%3A+%22health+check%22%7D
            port: 9880
          initialDelaySeconds: 5
          timeoutSeconds: 1
        volumeMounts:
        - name: config-volume-fluentd
          mountPath: /etc/fluent/config.d
        - name: buffer
          mountPath: "/var/log/fluentd-buffers"
      volumes:
        - name: config-volume-fluentd
          configMap:
            name: fluentd
        - name: buffer
          emptyDir: {}
