# Source: rundeck/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: rundeck
  labels:     
    app.kubernetes.io/name: rundeck
    helm.sh/chart: rundeck-0.3.6
    app.kubernetes.io/instance: rundeck
    app.kubernetes.io/managed-by: Helm
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: rundeck
    app.kubernetes.io/instance: rundeck
---
