# Source: orientdb/templates/secret.yaml
apiVersion: v1
kind: Secret
metadata:
  name: orientdb-secret
  labels:
    app: orientdb
    chart: orientdb-0.1.4
    release: orientdb
    heritage: Helm
data:
  
  root-password: "UVB3SDhtYzJIWg=="
---
