# Source: spark/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: spark
  labels:
    app.kubernetes.io/name: spark
    helm.sh/chart: spark-0.1.2
    app.kubernetes.io/instance: spark
    app.kubernetes.io/version: "0.0.1"
    app.kubernetes.io/managed-by: Helm
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: spark
      app.kubernetes.io/instance: spark
  template:
    metadata:
      labels:
        app.kubernetes.io/name: spark
        app.kubernetes.io/instance: spark
    spec:
      serviceAccountName: spark
      securityContext:
        {}
      containers:
        - name: spark
          securityContext:
            {}
          image: "nginx:stable"
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
          resources:
            {}
---
