# Source: spark/templates/serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: spark
  labels:
    app.kubernetes.io/name: spark
    helm.sh/chart: spark-0.1.2
    app.kubernetes.io/instance: spark
    app.kubernetes.io/version: "0.0.1"
    app.kubernetes.io/managed-by: Helm
---
