# Source: spark/templates/tests/test-connection.yaml
apiVersion: v1
kind: Pod
metadata:
  name: "spark-test-connection"
  labels:
    app.kubernetes.io/name: spark
    helm.sh/chart: spark-0.1.2
    app.kubernetes.io/instance: spark
    app.kubernetes.io/version: "0.0.1"
    app.kubernetes.io/managed-by: Helm
  annotations:
    "helm.sh/hook": test-success
spec:
  containers:
    - name: wget
      image: busybox
      command: ['wget']
      args:  ['spark:80']
  restartPolicy: Never
