# Source: kube-downscaler/templates/clusterrolebinding.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: kube-downscaler
  labels:
    app.kubernetes.io/name: kube-downscaler
    helm.sh/chart: kube-downscaler-0.6.2
    app.kubernetes.io/instance: kube-downscaler
    app.kubernetes.io/managed-by: Helm
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: "kube-downscaler"
subjects:
  - kind: ServiceAccount
    name: "kube-downscaler"
    namespace: default
---
