# Source: kube-downscaler/templates/serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: kube-downscaler
  labels:
    app.kubernetes.io/name: kube-downscaler
    helm.sh/chart: kube-downscaler-0.6.2
    app.kubernetes.io/instance: kube-downscaler
    app.kubernetes.io/managed-by: Helm
---
