# Source: druid/charts/postgresql/templates/secrets.yaml
apiVersion: v1
kind: Secret
metadata:
  name: druid-postgresql
  labels:
    app: postgresql
    chart: postgresql-8.6.4
    release: "druid"
    heritage: "Helm"
type: Opaque
data:
  postgresql-password: "ZHJ1aWQ="
---
