# Source: schema-registry/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: schema-registry
  labels:
    app: schema-registry
    chart: schema-registry-1.2.3
    release: schema-registry
    heritage: Helm
spec:
  selector:
    matchLabels:
      app: schema-registry
      release: schema-registry
  replicas: 1
  template:
    metadata:
      labels:
        app: schema-registry
        release: schema-registry
    spec:
      containers:
        - name: schema-registry
          image: "confluentinc/cp-schema-registry:5.0.1"
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8081
            - containerPort: 5555
              name: jmx
          livenessProbe:
            httpGet:
              path: /
              port: 8081
            initialDelaySeconds: 10
            timeoutSeconds: 5
          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: /
              port: 8081
            initialDelaySeconds: 10
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 5
          env:
          - name: SCHEMA_REGISTRY_HOST_NAME
            valueFrom:
              fieldRef:
                fieldPath: status.podIP
          - name: SCHEMA_REGISTRY_KAFKASTORE_BOOTSTRAP_SERVERS
            value: PLAINTEXT://schema-registry-kafka-headless:9092
          - name: SCHEMA_REGISTRY_KAFKASTORE_GROUP_ID
            value: schema-registry
          
          - name: JMX_PORT
            value: "5555"
          resources:
            {}
          volumeMounts:
      volumes:
---
