# Source: hoverfly/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: hoverfly-hoverfly
  labels:
    chart: "hoverfly-0.1.4"
spec:
  type: ClusterIP
  ports:
  - port: 8888
    targetPort: 8888
    protocol: TCP
    name: admin
  - port: 8500
    targetPort: 8500
    protocol: TCP
    name: proxy
  selector:
    app: hoverfly-hoverfly
---
