# Source: keycloak-proxy/templates/configmap.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: keycloak-proxy
  labels:
    app: keycloak-proxy
    chart: keycloak-proxy-0.0.3
    release: keycloak-proxy
    heritage: Helm
data:
  proxy.json: |
    {
       "target-url":"http://url-to-the-target-server.example.com",
       "bind-address":"0.0.0.0",
       "http-port":"8080",
       "applications":[
          {
             "base-path":"/",
             "adapter-config":{
                "realm":"REALM_NAME",
                "auth-server-url":"http://url-to-keycloak.example.com/auth",
                "ssl-required":"external",
                "resource":"CLIENT_ID",
                "credentials": {
                  "secret": "CLIENT_SECRET"
                }
             },
             "constraints":[
               {
                  "pattern":"/admin",
                  "roles-allowed":[
                    "admin"
                  ]
               }
             ],
             "proxy-address-forwarding": true
          }
       ]
    }
---
