# Source: oauth-proxy/templates/serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: oauth-proxy
  labels:
    app.kubernetes.io/name: oauth-proxy
    helm.sh/chart: oauth-proxy-0.1.9
    app.kubernetes.io/instance: oauth-proxy
    app.kubernetes.io/version: "0.0.1"
    app.kubernetes.io/managed-by: Helm
---
