# Source: oauth-proxy/templates/tests/test-connection.yaml
apiVersion: v1
kind: Pod
metadata:
  name: "oauth-proxy-test-connection"
  labels:
    app.kubernetes.io/name: oauth-proxy
    helm.sh/chart: oauth-proxy-0.1.9
    app.kubernetes.io/instance: oauth-proxy
    app.kubernetes.io/version: "0.0.1"
    app.kubernetes.io/managed-by: Helm
  annotations:
    "helm.sh/hook": test-success
spec:
  containers:
    - name: wget
      image: busybox
      command: ['wget']
      args:  ['oauth-proxy:80']
  restartPolicy: Never
