# Source: jaeger/templates/cassandra-schema-sa.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: jaeger-cassandra-schema
  labels:
    app.kubernetes.io/name: jaeger
    helm.sh/chart: jaeger-0.17.4
    app.kubernetes.io/instance: jaeger
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/component: cassandra-schema
---
