# Source: sentry-kubernetes/templates/secret.yaml
apiVersion: v1
kind: Secret
metadata:
  labels:     
    app: sentry-kubernetes
    heritage: Helm
    release: sentry-kubernetes
    chart: sentry-kubernetes-0.2.6
  name: sentry-kubernetes
type: Opaque
data:
  sentry.dsn: "PGNoYW5nZS1tZT4="
---
