# Source: mongodb-replicaset/templates/serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: mongodb-replicaset
  labels:
    app.kubernetes.io/name: mongodb-replicaset
    helm.sh/chart: mongodb-replicaset-0.2.1
    app.kubernetes.io/instance: mongodb-replicaset
    app.kubernetes.io/version: "0.0.1"
    app.kubernetes.io/managed-by: Helm
---
