# Source: mongodb-replicaset/templates/tests/test-connection.yaml
apiVersion: v1
kind: Pod
metadata:
  name: "mongodb-replicaset-test-connection"
  labels:
    app.kubernetes.io/name: mongodb-replicaset
    helm.sh/chart: mongodb-replicaset-0.2.1
    app.kubernetes.io/instance: mongodb-replicaset
    app.kubernetes.io/version: "0.0.1"
    app.kubernetes.io/managed-by: Helm
  annotations:
    "helm.sh/hook": test-success
spec:
  containers:
    - name: wget
      image: busybox
      command: ['wget']
      args:  ['mongodb-replicaset:80']
  restartPolicy: Never
