# Source: keycloak/templates/keycloak-secret.yaml
apiVersion: v1
kind: Secret
metadata:
  name: keycloak-http
  labels:
    app: keycloak
    chart: keycloak-0.6.0
    release: "keycloak"
    heritage: "Helm"
type: Opaque
data:
  password: "Q1hGVEFEZEEwWQ=="
---
