# Source: keycloak/charts/postgresql/templates/secrets.yaml
apiVersion: v1
kind: Secret
metadata:
  name: keycloak-postgresql
  labels:
    app: postgresql
    chart: postgresql-0.12.0
    release: keycloak
    heritage: Helm
type: Opaque
data:
  
  postgres-password: "M2pIN0EwTFlObQ=="
---
