# Source: keycloak/templates/test/test-pod.yaml
apiVersion: v1
kind: Pod
metadata:
  name: keycloak-test
  labels:
    app: keycloak
    chart: keycloak-0.6.0
    release: "keycloak"
    heritage: "Helm"
  annotations:
    "helm.sh/hook": test-success
spec:
  containers:
    - name: keycloak-test
      image: "unguiculus/docker-python3-phantomjs-selenium:v1"
      imagePullPolicy: IfNotPresent
      command:
        - python3
        - /tests/test.py
      env:
        - name: KEYCLOAK_USER
          value: keycloak
        - name: KEYCLOAK_PASSWORD
          valueFrom:
            secretKeyRef:
              name: keycloak-http
              key: password
      volumeMounts:
        - name: tests
          mountPath: /tests
  volumes:
    - name: tests
      configMap:
        name: keycloak-test
  restartPolicy: Never
