# Source: kube-janitor/templates/service-account.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: kube-janitor
  labels:
    app: kube-janitor
    chart: kube-janitor-0.1.2
    release: kube-janitor
    heritage: Helm
---
