# Source: grafana/templates/serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: grafana
  labels:
    app.kubernetes.io/name: grafana
    helm.sh/chart: grafana-0.1.4
    app.kubernetes.io/instance: grafana
    app.kubernetes.io/version: "0.0.1"
    app.kubernetes.io/managed-by: Helm
---
