# Source: kube-registry-proxy/templates/daemon.yaml
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: kube-registry-proxy-kube-registry-proxy
  labels:
    heritage: "Helm"
    release: "kube-registry-proxy"
    chart: "kube-registry-proxy-0.3.4"
spec:
  selector:
    matchLabels:
      app: kube-registry-proxy-kube-registry-proxy
  template:
    metadata:
      name: kube-registry-proxy-kube-registry-proxy
      labels:
        app: kube-registry-proxy-kube-registry-proxy
    spec:
      containers:
      - name: kube-registry-proxy
        image: "k8s.gcr.io/kube-registry-proxy:0.4"
        imagePullPolicy: IfNotPresent
        env:
        - name: REGISTRY_HOST
          value: "gcr.io"
        - name: REGISTRY_PORT
          value: ""
        ports:
        - containerPort: 80
          hostPort: 5555
          hostIP: 127.0.0.1
