# Source: patroni/templates/serviceaccount-patroni.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: patroni
  labels:
    app: patroni
    chart: patroni-0.16.3
    release: patroni
    heritage: Helm
---
