# Source: docker-registry/templates/serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: docker-registry
  labels:
    app.kubernetes.io/name: docker-registry
    helm.sh/chart: docker-registry-0.3.1
    app.kubernetes.io/instance: docker-registry
    app.kubernetes.io/version: "0.0.1"
    app.kubernetes.io/managed-by: Helm
---
