# Source: jenkins-operator/templates/rbac_service_account.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: jenkins-operator
  labels:
    helm.sh/chart: jenkins-operator-0.3.1
    app.kubernetes.io/name: jenkins-operator
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/instance: jenkins-operator
    app.kubernetes.io/version: 0.3.0
---
