# Source: kubeless/templates/controller-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubeless-kubeless-controller-manager
  labels:
    app: kubeless
    heritage: "Helm"
    release: "kubeless"
    chart: kubeless-2.1.3
    kubeless: controller
spec:
  selector:
    matchLabels:
      kubeless: controller
  replicas: 1
  template:
    metadata:
      labels:
        kubeless: controller
        app: kubeless
        release: kubeless
    spec:
      containers:
      - name: kubeless-function-controller
        image: "kubeless/function-controller:v1.0.5"
        imagePullPolicy: IfNotPresent
        env:
        - name: KUBELESS_NAMESPACE
          value: default
        resources:
          {}
      - name: http-trigger-controller
        image: "kubeless/http-trigger-controller:v1.0.1"
        imagePullPolicy: IfNotPresent
        env:
        - name: KUBELESS_NAMESPACE
          value: default
        resources:
          {}
      - name: cronjob-trigger-controller
        image: "kubeless/cronjob-trigger-controller:v1.0.1"
        imagePullPolicy: IfNotPresent
        env:
        - name: KUBELESS_NAMESPACE
          value: default
        resources:
          {}
