# Source: mongodb/templates/tests/test-connection.yaml
apiVersion: v1
kind: Pod
metadata:
  name: "mongodb-test-connection"
  labels:
    app.kubernetes.io/name: mongodb
    helm.sh/chart: mongodb-0.1.2
    app.kubernetes.io/instance: mongodb
    app.kubernetes.io/version: "0.0.1"
    app.kubernetes.io/managed-by: Helm
  annotations:
    "helm.sh/hook": test-success
spec:
  containers:
    - name: wget
      image: busybox
      command: ['wget']
      args:  ['mongodb:80']
  restartPolicy: Never
