# Source: kubernetes-vault/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubernetes-vault-kubernetes-vault
  labels:
    app: kubernetes-vault
    chart: kubernetes-vault-0.2.3
    release: kubernetes-vault
    heritage: Helm
spec:
  replicas: 3
  selector:
    matchLabels:
      app: kubernetes-vault
      release: kubernetes-vault
  template:
    metadata:
      labels:
        app: kubernetes-vault
        release: kubernetes-vault
    spec:
      serviceAccountName: kubernetes-vault-kubernetes-vault
      volumes:
        - name: config-volume
          configMap:
            name: kubernetes-vault-kubernetes-vault
      containers:
        - name: kubernetes-vault
          image: "boostport/kubernetes-vault:v0.5.2"
          imagePullPolicy: Always
          env:
            - name: KUBERNETES_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
          volumeMounts:
          - name: config-volume
            mountPath: /kubernetes-vault
          resources:
            limits:
              cpu: 100m
              memory: 128Mi
            requests:
              cpu: 100m
              memory: 128Mi
