# Source: kubernetes-vault/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: kubernetes-vault-kubernetes-vault
  labels:
    app: kubernetes-vault
    chart: kubernetes-vault-0.2.3
    release: kubernetes-vault
    heritage: Helm
spec:
  clusterIP: None
  ports:
    - name: port 
      port: 80
  selector:
    run: kubernetes-vault-kubernetes-vault
    app: kubernetes-vault
    release: kubernetes-vault
---
