# Source: kube-ops-view/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kube-ops-view
  labels:
    app.kubernetes.io/name: kube-ops-view
    helm.sh/chart: kube-ops-view-0.1.1
    app.kubernetes.io/instance: kube-ops-view
    app.kubernetes.io/version: "0.0.1"
    app.kubernetes.io/managed-by: Helm
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: kube-ops-view
      app.kubernetes.io/instance: kube-ops-view
  template:
    metadata:
      labels:
        app.kubernetes.io/name: kube-ops-view
        app.kubernetes.io/instance: kube-ops-view
    spec:
      serviceAccountName: kube-ops-view
      securityContext:
        {}
      containers:
        - name: kube-ops-view
          securityContext:
            {}
          image: "nginx:stable"
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
          resources:
            {}
---
