# Source: kube-ops-view/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: kube-ops-view
  labels:
    app.kubernetes.io/name: kube-ops-view
    helm.sh/chart: kube-ops-view-0.1.1
    app.kubernetes.io/instance: kube-ops-view
    app.kubernetes.io/version: "0.0.1"
    app.kubernetes.io/managed-by: Helm
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: kube-ops-view
    app.kubernetes.io/instance: kube-ops-view
---
