# Source: consul/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: consul
  labels:
    app.kubernetes.io/name: consul
    helm.sh/chart: consul-0.1.5
    app.kubernetes.io/instance: consul
    app.kubernetes.io/version: "0.0.1"
    app.kubernetes.io/managed-by: Helm
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: consul
    app.kubernetes.io/instance: consul
---
