# Source: aws-alb-ingress-controller/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: aws-alb-ingress-controller
  labels:
    app.kubernetes.io/name: aws-alb-ingress-controller
    helm.sh/chart: aws-alb-ingress-controller-1.0.4
    app.kubernetes.io/instance: aws-alb-ingress-controller
    app.kubernetes.io/managed-by: Helm
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: aws-alb-ingress-controller
      app.kubernetes.io/instance: aws-alb-ingress-controller
  template:
    metadata:
      labels:
        app.kubernetes.io/name: aws-alb-ingress-controller
        app.kubernetes.io/instance: aws-alb-ingress-controller
    spec:
      containers:
        - name: aws-alb-ingress-controller
          image: "docker.io/amazon/aws-alb-ingress-controller:v1.1.8"
          imagePullPolicy: IfNotPresent
          args:
            - --cluster-name=k8s
            - --ingress-class=alb
          
            - --aws-region=us-east-2
            - --aws-vpc-id=vpc-xxx
          env:
          ports:
            - name: health
              containerPort: 10254
              protocol: TCP
          resources: 
            {}
      serviceAccountName: aws-alb-ingress-controller
      terminationGracePeriodSeconds: 60
