# Source: aws-alb-ingress-controller/templates/serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: aws-alb-ingress-controller
  labels:
    app.kubernetes.io/name: aws-alb-ingress-controller
    helm.sh/chart: aws-alb-ingress-controller-1.0.4
    app.kubernetes.io/instance: aws-alb-ingress-controller
    app.kubernetes.io/managed-by: Helm
---
