# Source: kube-spot-termination-notice-handler/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kube-spot-termination-notice-handler
  labels:
    app.kubernetes.io/name: kube-spot-termination-notice-handler
    helm.sh/chart: kube-spot-termination-notice-handler-0.4.1
    app.kubernetes.io/instance: kube-spot-termination-notice-handler
    app.kubernetes.io/version: "0.0.1"
    app.kubernetes.io/managed-by: Helm
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: kube-spot-termination-notice-handler
      app.kubernetes.io/instance: kube-spot-termination-notice-handler
  template:
    metadata:
      labels:
        app.kubernetes.io/name: kube-spot-termination-notice-handler
        app.kubernetes.io/instance: kube-spot-termination-notice-handler
    spec:
      serviceAccountName: kube-spot-termination-notice-handler
      securityContext:
        {}
      containers:
        - name: kube-spot-termination-notice-handler
          securityContext:
            {}
          image: "nginx:stable"
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
          resources:
            {}
---
