# Source: kube-spot-termination-notice-handler/templates/serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: kube-spot-termination-notice-handler
  labels:
    app.kubernetes.io/name: kube-spot-termination-notice-handler
    helm.sh/chart: kube-spot-termination-notice-handler-0.4.1
    app.kubernetes.io/instance: kube-spot-termination-notice-handler
    app.kubernetes.io/version: "0.0.1"
    app.kubernetes.io/managed-by: Helm
---
