# Source: kube-spot-termination-notice-handler/templates/tests/test-connection.yaml
apiVersion: v1
kind: Pod
metadata:
  name: "kube-spot-termination-notice-handler-test-connection"
  labels:
    app.kubernetes.io/name: kube-spot-termination-notice-handler
    helm.sh/chart: kube-spot-termination-notice-handler-0.4.1
    app.kubernetes.io/instance: kube-spot-termination-notice-handler
    app.kubernetes.io/version: "0.0.1"
    app.kubernetes.io/managed-by: Helm
  annotations:
    "helm.sh/hook": test-success
spec:
  containers:
    - name: wget
      image: busybox
      command: ['wget']
      args:  ['kube-spot-termination-notice-handler:80']
  restartPolicy: Never
