# Source: haproxy-ingress/templates/controller-poddisruptionbudget.yaml
apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  labels:
    app: haproxy-ingress-controller
    chart: haproxy-ingress-0.0.28
    component: "controller"
    release: haproxy-ingress
    heritage: Helm
  name: haproxy-ingress-controller
spec:
  selector:
    matchLabels:
      app: haproxy-ingress-controller
      release: haproxy-ingress
      component: "controller"
  minAvailable: 1
---
