# Source: haproxy-ingress/templates/controller-service.yaml
apiVersion: v1
kind: Service
metadata:
  labels:
    app: haproxy-ingress-controller
    chart: haproxy-ingress-0.0.28
    component: "controller"
    release: haproxy-ingress
    heritage: Helm
  name: haproxy-ingress-controller
  namespace: default
spec:
  externalTrafficPolicy: "Local"
  ports:
    - name: "http-80"
      port: 80
      protocol: TCP
      targetPort: http
    - name: "https-443"
      port: 443
      protocol: TCP
      targetPort: https
  selector:
    app: haproxy-ingress-controller
    component: "controller"
    release: haproxy-ingress
  type: "LoadBalancer"
---
