# Source: haproxy-ingress/templates/role.yaml
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: Role
metadata:
  labels:
    app: haproxy-ingress
    chart: haproxy-ingress-0.0.28
    release: haproxy-ingress
    heritage: Helm
  name: haproxy-ingress
  namespace: default
rules:
  - apiGroups:
      - ""
    resources:
      - pods
      - secrets
      - namespaces
    verbs:
      - get
  - apiGroups:
      - ""
    resources:
      - configmaps
      - endpoints
    verbs:
      - get
      - create
      - update
---
