# Source: haproxy-ingress/templates/rolebinding.yaml
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: RoleBinding
metadata:
  labels:
    app: haproxy-ingress
    chart: haproxy-ingress-0.0.28
    release: haproxy-ingress
    heritage: Helm
  name: haproxy-ingress
  namespace: default
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: haproxy-ingress
subjects:
  - kind: ServiceAccount
    name: haproxy-ingress
    namespace: default
  - apiGroup: rbac.authorization.k8s.io
    kind: User
    name: haproxy-ingress
---
