# Source: haproxy-ingress/templates/serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app: haproxy-ingress
    chart: haproxy-ingress-0.0.28
    release: haproxy-ingress
    heritage: Helm
  name: haproxy-ingress
  namespace: default
---
