# Source: istio/templates/addons-prometheus-configmap.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: istio-istio-prometheus
  labels:
    app: istio
    heritage: "Helm"
    release: "istio"
    chart: istio-0.3.0
data:
  prometheus.yml: |-
    global:
      scrape_interval: 15s
    scrape_configs:

    - job_name: 'mixer'
      # Override the global default and scrape targets from this job every 5 seconds.
      scrape_interval: 5s
      # metrics_path defaults to '/metrics'
      # scheme defaults to 'http'.
      static_configs:
      - targets: ['istio-istio-mixer:42422']
---
