# Source: istio/templates/addons-zipkin-svc.yaml
apiVersion: v1
kind: Service
metadata:
  name: istio-istio-zipkin
  labels:
    app: istio
    heritage: "Helm"
    release: "istio"
    chart: istio-0.3.0
spec:
  type: ClusterIP
  ports:
  - name: http
    port: 9411
  selector:
    app: istio
    component: istio-istio-zipkin
    release: istio
---
