# Source: istio/templates/addons-servicegraph-svc.yaml
apiVersion: v1
kind: Service
metadata:
  name: istio-istio-servicegraph
  labels:
    app: istio
    heritage: "Helm"
    release: "istio"
    chart: istio-0.3.0
spec:
  type: ClusterIP
  ports:
  - name: http
    port: 8088
  selector:
    app: istio
    component: istio-istio-servicegraph
    release: istio
---
