# Source: istio/templates/ca-deployment.yaml
apiVersion: v1
kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: istio-istio-ca
  labels:
    app: istio
    heritage: "Helm"
    release: "istio"
    chart: istio-0.3.0
    component: istio-istio-ca
    istio: istio-istio-ca
spec:
  replicas: 1
  template:
    metadata:
      annotations:
      labels:
        app: istio
        heritage: "Helm"
        release: "istio"
        chart: istio-0.3.0
        component: istio-istio-ca
        istio: istio-istio-ca
    spec:
      serviceAccountName: istio-istio-ca-service-account
      containers:
      - name: ca
        image: "docker.io/istio/istio-ca:0.1.6"
        imagePullPolicy: IfNotPresent
        env:
        - name: NAMESPACE
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
        resources:
          limits:
            cpu: 100m
            memory: 128Mi
          requests:
            cpu: 100m
            memory: 128Mi
---
