# Source: istio/templates/ingress-service-account.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: istio-istio-ingress-service-account
  labels:
    app: istio
    heritage: "Helm"
    release: "istio"
    chart: istio-0.3.0
    istio: istio-istio-ingress
---
