# Source: istio/templates/mixer-svc.yaml
apiVersion: v1
kind: Service
metadata:
  name: istio-istio-mixer
  labels:
    app: istio
    heritage: "Helm"
    release: "istio"
    chart: istio-0.3.0
    istio: istio-istio-mixer
  annotations:
spec:
  type: ClusterIP
  ports:
  - name: tcp
    port: 9091
  - name: configapi
    port: 9094
  - name: prometheus
    port: 42422
  selector:
    app: istio
    component: istio-istio-mixer
    release: istio
    istio: istio-istio-mixer
---
