# Source: istio/templates/pilot-deployment.yaml
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: istio-istio-istio-pilot
  labels:
    app: istio
    heritage: "Helm"
    release: "istio"
    chart: istio-0.3.0
    component: istio-istio-istio-pilot
    istio: istio-istio-istio-pilot
spec:
  replicas: 1
  template:
    metadata:
      annotations:
          alpha.istio.io/sidecar: "ignore"
      labels:
        app: istio
        heritage: "Helm"
        release: "istio"
        chart: istio-0.3.0
        component: istio-istio-istio-pilot
        istio: istio-istio-istio-pilot
    spec:
      serviceAccountName: istio-istio-pilot-service-account
      containers:
      - name: discovery
        image: "docker.io/istio/pilot:0.1.6"
        imagePullPolicy: Always
        args: ["discovery", "-v", "2"]
        ports:
        - containerPort: 8080
        env:
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
        resources:
          limits:
            cpu: 100m
            memory: 128Mi
          requests:
            cpu: 100m
            memory: 128Mi
      - name: apiserver
        image: "docker.io/istio/pilot:0.1.6"
        imagePullPolicy: Always
        args: ["apiserver", "-v", "2"]
        ports:
        - containerPort: 8081
        env:
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
        resources:
          limits:
            cpu: 100m
            memory: 128Mi
          requests:
            cpu: 100m
            memory: 128Mi
