# Source: couchdb/templates/headless.yaml
apiVersion: v1
kind: Service
metadata:
  name: couchdb-couchdb
  labels:
    app: couchdb
    chart: couchdb-1.3.1
    release: couchdb
    heritage: Helm
spec:
  clusterIP: None
  ports:
    - name: couchdb
      port: 5984
  selector:
    app: couchdb
    release: couchdb
---
