# Source: couchdb/templates/secrets.yaml
apiVersion: v1
kind: Secret
metadata:
  name: couchdb-couchdb
  labels:
    app: couchdb-couchdb
    chart: "couchdb-1.3.1"
    release: "couchdb"
    heritage: "Helm"
type: Opaque
data:
  adminUsername: "YWRtaW4="
  adminPassword: "RFloUDdHMUtXWVlHQ2Y0eGhMWVA="
  cookieAuthSecret: "NVNEandZTU1qbXdhUDUzZGcxMEY="
---
