# Source: vault/templates/pdb.yaml
apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  name: vault
spec:
  maxUnavailable: 1
  selector:
    matchLabels:
      app: vault
      release: vault
---
