# Source: cassandra-operator/templates/service_account.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app: cassandra-operator
    chart: cassandra-operator-0.3.5
    heritage: Helm
    release: cassandra-operator
  name: cassandra-operator
---
