# Source: burrow/templates/config-configs.yaml
kind: ConfigMap
apiVersion: v1
metadata:
  labels:
    app: burrow
    chart: "burrow-0.4.3"
    heritage: Helm
    release: burrow
  name: burrow-config-000
data:
  config.toml: |-
    [chain]
    assert_chain_id = "simpleTestChain"
    major_version = 0
    minor_version = 17
    genesis_file = "genesis.json"
      [chain.consensus]
      name = "tendermint"
      major_version = 0
      minor_version = 8
      relative_root = "tendermint"
      [chain.manager]
      name = "burrowmint"
      major_version = 0
      minor_version = 17
      relative_root = "burrowmint"
    [servers]
      [servers.bind]
      address = ""
      port = 1337
      [servers.tls]
      tls = false
      cert_path = ""
      key_path = ""
      [servers.cors]
      enable = false
      allow_origins = []
      allow_credentials = false
      allow_methods = []
      allow_headers = []
      expose_headers = []
      max_age = 0
      [servers.http]
      json_rpc_endpoint = "/rpc"
      [servers.websocket]
      endpoint = "/socketrpc"
      max_sessions = 50
      read_buffer_size = 4096
      write_buffer_size = 4096
      [servers.tendermint]
      rpc_local_address = "0.0.0.0:46657"
      endpoint = "/websocket"
      [servers.logging]
      console_log_level = "info"
      file_log_level = "warn"
      log_file = "burrow-logs.log"
    [tendermint]
    private_validator_file = "priv_validator.json"
      [tendermint.configuration]
      moniker = "myOrg-simpleTestChain-validator-000"
      seeds = "burrow-peer-000:46656"
      fast_sync = true
      db_backend = "leveldb"
      log_level = "info"
      node_laddr = "tcp://0.0.0.0:46656"
      rpc_laddr = "tcp://0.0.0.0:46657"
      proxy_app = "tcp://127.0.0.1:46658"
        [tendermint.configuration.p2p]
        dial_timeout_seconds = 1
        handshake_timeout_seconds = 5
        max_num_peers = 20
        authenticated_encryption = true
        send_rate = 512000
        recv_rate = 512000
        fuzz_enable = false # use the fuzz wrapped conn
        fuzz_active = false # toggle fuzzing
        fuzz_mode = "drop"  # eg. drop, delay
        fuzz_max_delay_milliseconds = 3000
        fuzz_prob_drop_rw = 0.2
        fuzz_prob_drop_conn = 0.00
        fuzz_prob_sleep = 0.00
    [burrowmint]
    db_backend = "leveldb"
    tendermint_host = "0.0.0.0:46657"
    [logging]
      [logging.root_sink]
        [logging.root_sink.transform]
          transform_type = "filter"
          filter_mode = "exclude_when_all_match"
          [[logging.root_sink.transform.predicates]]
            key_regex = "log_channel"
            value_regex = "Trace"
        [[logging.root_sink.sinks]]
          [logging.root_sink.sinks.output]
            output_type = "stderr"
            format = "json"
---
