# Source: burrow/templates/secret-genesis.yaml
kind: Secret
apiVersion: v1
metadata:
  labels:
    app: burrow
    chart: "burrow-0.4.3"
    heritage: Helm
    release: burrow
  name: burrow-genesis
type: Opaque
data:
  genesis.json:
---
