# Source: burrow/templates/secret-keys.yaml
apiVersion: v1
kind: Secret
metadata:
  labels:
    app: burrow
    chart: "burrow-0.4.3"
    heritage: Helm
    release: burrow
  name: burrow-keys
type: Opaque
data:
  {}
---
