# Source: burrow/templates/service-rpc.yaml
apiVersion: v1
kind: Service
metadata:
  labels:
    app: burrow
    chart: burrow-0.4.3
    release: burrow
    heritage: Helm
  name:  burrow-rpc
spec:
  type: ClusterIP
  ports:
    - name: rpc
      port: 46657
      targetPort: rpc
      protocol: TCP
  selector:
    app: burrow
    release: burrow
    nodeNumber: "000"
---
