# Source: burrow/templates/service-api.yaml
apiVersion: v1
kind: Service
metadata:
  labels:
    app:  burrow
    chart: burrow-0.4.3
    release: burrow
    heritage: Helm
  name: burrow-api
spec:
  type: ClusterIP
  sessionAffinity: ClientIP
  ports:
    - name: api
      port: 1337
      targetPort: api
      protocol: TCP
  selector:
    app: burrow
    release: burrow
---
