# Source: artifactory/templates/svc.yaml
apiVersion: v1
kind: Service
metadata:
  name: artifactory-artifactory
  labels:
    heritage: "Helm"
    release: "artifactory"
    chart: "artifactory-5.2.2"
    app: artifactory-artifactory
spec:
  ports:
  - port: 8081
    targetPort: 8081
    protocol: TCP
    name: http
  selector:
    app: artifactory-artifactory
  type: ClusterIP
---
