# Source: vaultingkube/templates/rbac.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    app: vaultingkube
    chart: vaultingkube-0.1.4
    release: vaultingkube
    heritage: Helm
  name: vaultingkube
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: vaultingkube
subjects:
- kind: ServiceAccount
  name: vaultingkube
  namespace: default
