# Source: vaultingkube/templates/serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app: vaultingkube
    chart: vaultingkube-0.1.4
    release: vaultingkube
    heritage: Helm
  name: vaultingkube
---
