# Source: xray/charts/rabbitmq-ha/templates/secret.yaml
apiVersion: v1
kind: Secret
metadata:
  name: xray-rabbitmq-ha
  labels:
    app: rabbitmq-ha
    chart: "rabbitmq-ha-1.5.2"
    release: "xray"
    heritage: "Helm"
type: Opaque
data:
  
  rabbitmq-password: "cDdUM2BxLmV6XCIlI29ONiUzR3M/TW4="
  
  
  rabbitmq-erlang-cookie: "WFJBWVJBQkJJVE1RQ0xVU1RFUg=="
---
