# Source: solr/templates/poddisruptionbudget.yaml
apiVersion: "policy/v1beta1"
kind: "PodDisruptionBudget"
metadata:
  name: "solr"
  labels:
    app.kubernetes.io/name: solr
    app.kubernetes.io/instance: solr
    app.kubernetes.io/managed-by: Helm
    helm.sh/chart: solr-1.5.5
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: "solr"
      app.kubernetes.io/instance: "solr"
      app.kubernetes.io/component: "server"
  maxUnavailable: 1
---
