# Source: solr/templates/service-headless.yaml
apiVersion: "v1"
kind: "Service"
metadata:
  name: "solr-headless"
  labels:
    app.kubernetes.io/name: solr
    app.kubernetes.io/instance: solr
    app.kubernetes.io/managed-by: Helm
    helm.sh/chart: solr-1.5.5
spec:
  clusterIP: "None"
  ports:
    - port: 8983
      name: "solr-headless"
  selector:
    app.kubernetes.io/name: "solr"
    app.kubernetes.io/instance: "solr"
    app.kubernetes.io/component: "server"
---
