# Source: logstash/templates/patterns-config.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: logstash-patterns
  labels:
    app: logstash
    chart: logstash-0.9.6
    release: logstash
    heritage: Helm
data:
---
