# Source: logstash/templates/poddisruptionbudget.yaml
apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  name: logstash
  labels:
    app: logstash
    chart: logstash-0.9.6
    release: logstash
    heritage: Helm
spec:
  selector:
    matchLabels:
      app: logstash
      release: logstash
  maxUnavailable: 1
---
