# Source: cockroachdb/templates/serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: cockroachdb
  labels:
    app.kubernetes.io/name: cockroachdb
    helm.sh/chart: cockroachdb-0.1.2
    app.kubernetes.io/instance: cockroachdb
    app.kubernetes.io/version: "0.0.1"
    app.kubernetes.io/managed-by: Helm
---
