# Source: kafka/charts/zookeeper/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: kafka-zookeeper
  labels:
    app: zookeeper
    chart: zookeeper-2.1.0
    release: kafka
    heritage: Helm
spec:
  type: ClusterIP
  ports:
    - name: client
      port: 2181
      protocol: TCP
      targetPort: client
  selector:
    app: zookeeper
    release: kafka
---
