# Source: honeydipper/templates/daemon-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: honeydipper
  labels:
    app.kubernetes.io/name: honeydipper
    helm.sh/chart: honeydipper-0.1.5
    app.kubernetes.io/instance: honeydipper
    app.kubernetes.io/managed-by: Helm
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: honeydipper
      app.kubernetes.io/instance: honeydipper
  template:
    metadata:
      labels:
        app.kubernetes.io/name: honeydipper
        app.kubernetes.io/instance: honeydipper
    spec:
      containers:
        - name: honeydipper-redis
          image: "redis:5"
        - name: honeydipper
          image: "honeydipper/honeydipper:0.1.10"
          imagePullPolicy: IfNotPresent
          env:
            - name: REPO
              value: https://github.com/honeydipper/honeydipper-config-essentials
          ports:
            - name: webhook
              containerPort: 8080
          readinessProbe:
            httpGet:
              path: /hz/alive
              port: 8080
            initialDelaySeconds: 20
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /hz/alive
              port: 8080
            initialDelaySeconds: 20
            periodSeconds: 20
---
