# Source: mysqlha/templates/configmap.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: mysqlha
  labels:
    app: mysqlha
    chart: "mysqlha-2.0.2"
    release: "mysqlha"
    heritage: "Helm"
data:
  master.cnf: |
    # Apply this config only on the master.
    [mysqld]
    log-bin
    skip_name_resolve
  slave.cnf: |
    # Apply this config only on slaves.
    [mysqld]
    super-read-only
    skip_name_resolve
  server-id.cnf: |
    [mysqld]
    server-id=@@SERVER_ID@@
  create-replication-user.sh: |-
    #!/bin/bash
    set -e

    mysql -h 127.0.0.1 --verbose -e "CREATE USER IF NOT EXISTS '${MYSQL_REPLICATION_USER}' IDENTIFIED BY '${MYSQL_REPLICATION_PASSWORD}';"
    mysql -h 127.0.0.1 --verbose -e "GRANT PROCESS, RELOAD, REPLICATION SLAVE, REPLICATION CLIENT ON *.* TO '${MYSQL_REPLICATION_USER}';"
    mysql -h 127.0.0.1 --verbose -e "FLUSH PRIVILEGES;"
---
