# Source: mysqlha/templates/secret.yaml
apiVersion: v1
kind: Secret
metadata:
  name: mysqlha
  labels:
    app: mysqlha
    chart: "mysqlha-2.0.2"
    release: "mysqlha"
    heritage: "Helm"
type: Opaque
data:
  mysql-root-password: "eHB0QkdxemEzdnkw"
  mysql-replication-password: "eUhQNmNNSWtBaEZS"
---
