# Source: goldfish/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: "goldfish-goldfish"
  labels:
    app: "goldfish"
    release: "goldfish"
    heritage: "Helm"
    chart: "goldfish-0.2.9"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: "goldfish"
      release: "goldfish"
  template:
    metadata:
      labels:
        app: goldfish
        release: goldfish
    spec:
      containers:
        - name: goldfish
          image: "caiyeon/goldfish:0.9.0"
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8000
          env:
          - name: VAULT_TOKEN
            valueFrom:
              secretKeyRef:
                name: goldfish-goldfish
                key: vault-token
          livenessProbe:
            httpGet:
              path: /
              port: 8000
          readinessProbe:
            httpGet:
              path: /
              port: 8000
          env:
            - name: GOLDFISH_PORT
              value: "8000"
            - name: GOLDFISH_CONFIG
              valueFrom:
                configMapKeyRef:
                  name: goldfish-goldfish
                  key: config
            - name: VAULT_TOKEN
              valueFrom:
                secretKeyRef:
                  name: goldfish-goldfish
                  key: vault-token
          resources:
            {}
