# Source: goldfish/templates/secret.yaml
apiVersion: v1
kind: Secret
metadata:
  name: "goldfish-goldfish"
  labels:
    app: "goldfish"
    release: "goldfish"
    heritage: "Helm"
    chart: "goldfish-0.2.9"
type: Opaque
data:
  vault-token: ""
---
