# Source: gogs/templates/secrets.yaml
apiVersion: v1
kind: Secret
metadata:
  name: gogs-gogs
  labels:
    app: gogs-gogs
    chart: "gogs-0.7.14"
    release: "gogs"
    heritage: "Helm"
type: Opaque
data:
  postgresql-user: "Z29ncw=="
---
