# Source: gogs/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: gogs-gogs
  labels:
    chart: "gogs-0.7.14"
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 3000
    name: gogs-http
  - port: 22
    targetPort: 22
    name: gogs-ssh
  selector:
    app: gogs-gogs
---
