# Source: gogs/charts/postgresql/templates/svc-headless.yaml
apiVersion: v1
kind: Service
metadata:
  name: gogs-postgresql-headless
  labels:
    app: postgresql
    chart: postgresql-8.6.4
    release: "gogs"
    heritage: "Helm"
spec:
  type: ClusterIP
  clusterIP: None
  ports:
    - name: tcp-postgresql
      port: 5432
      targetPort: tcp-postgresql
  selector:
    app: postgresql
    release: "gogs"
---
