# Source: kubewatch/templates/clusterrole.yaml
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  labels:
    app: kubewatch
    chart: kubewatch-0.3.1
    heritage: Helm
    release: kubewatch
  name: kubewatch
rules:
  - apiGroups:
      - ""
    resources:
      - pods
      - namespaces
      - services
      - deployments
      - replicationcontrollers
      - replicasets
      - daemonsets
    verbs:
      - list
      - watch
---
