# Source: kubewatch/templates/deployment.yaml
apiVersion: apps/v1beta2
kind: Deployment
metadata:
  labels:
    app: kubewatch
    chart: kubewatch-0.3.1
    heritage: "Helm"
    release: "kubewatch"
  name: kubewatch
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kubewatch
      release: kubewatch
  template:
    metadata:
      annotations:
        checksum/config-map: ab659f99abc34aa92c15fea853c0d1a60980ae87a90e5724dcc089e31e756c49
      labels:
        app: kubewatch
        release: "kubewatch"
    spec:
      containers:
      - name: kubewatch
        image: tuna/kubewatch:v0.0.3
        imagePullPolicy: IfNotPresent
        volumeMounts:
        - name: kubewatch-config-map
          mountPath: /root
        resources:
          {}
      serviceAccountName: kubewatch
      tolerations:
        []
      restartPolicy: Always
      volumes:
      - name: kubewatch-config-map
        configMap:
          name: kubewatch-config
