# Source: kubewatch/templates/servieaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app: kubewatch
    chart: kubewatch-0.3.1
    heritage: Helm
    release: kubewatch
  name: kubewatch
---
