# Source: chartmuseum/templates/secret.yaml
apiVersion: v1
kind: Secret
metadata:
  name: chartmuseum-chartmuseum
  labels:
    app: chartmuseum
    chart: chartmuseum-1.4.0
    heritage: "Helm"
    release: "chartmuseum"
type: Opaque
data:
---
