# Source: puppet-forge/templates/pvc.yaml
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: puppet-forge-claim
  namespace: default
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 8Gi
---
