# Source: spring-cloud-data-flow/templates/metrics-service.yaml
kind: Service
apiVersion: v1
metadata:
  name: spring-cloud-data-flow-data-flow-metrics
  labels:
    app: spring-cloud-data-flow
    component: metrics
    chart: "spring-cloud-data-flow-0.2.8"
    release: "spring-cloud-data-flow"
    heritage: "Helm"
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: http
      name: http
  selector:
    app: spring-cloud-data-flow
    component: metrics
    release: spring-cloud-data-flow
---
