# Source: spring-cloud-data-flow/charts/redis/templates/pvc.yaml
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: spring-cloud-data-flow-redis
  labels:
    app: spring-cloud-data-flow-redis
    chart: "redis-1.1.11"
    release: "spring-cloud-data-flow"
    heritage: "Helm"
spec:
  accessModes:
    - "ReadWriteOnce"
  resources:
    requests:
      storage: "8Gi"
---
