# Source: spring-cloud-data-flow/templates/secrets.yaml
apiVersion: v1
kind: Secret
metadata:
  name: spring-cloud-data-flow-data-flow
  labels:
    app: spring-cloud-data-flow
    chart: "spring-cloud-data-flow-0.2.8"
    release: "spring-cloud-data-flow"
    heritage: "Helm"
type: Opaque
data:
  data-flow-admin-password: "YWRtaW4="
  data-flow-password: "cGFzc3dvcmQ="
---
