# Source: spring-cloud-data-flow/templates/server-rbac.yaml
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: spring-cloud-data-flow-data-flow
  labels:
    app: spring-cloud-data-flow
    chart: "spring-cloud-data-flow-0.2.8"
    release: "spring-cloud-data-flow"
    heritage: "Helm"
roleRef:
  kind: Role
  name: spring-cloud-data-flow-data-flow
  apiGroup: rbac.authorization.k8s.io
subjects:
- kind: ServiceAccount
  name: spring-cloud-data-flow-data-flow
---
