# Source: spring-cloud-data-flow/templates/service-account.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: spring-cloud-data-flow-data-flow
  labels:
    app: spring-cloud-data-flow
    chart: "spring-cloud-data-flow-0.2.8"
    release: "spring-cloud-data-flow"
    heritage: "Helm"
---
