# Source: spring-cloud-data-flow/charts/redis/templates/svc.yaml
apiVersion: v1
kind: Service
metadata:
  name: spring-cloud-data-flow-redis
  labels:
    app: spring-cloud-data-flow-redis
    chart: "redis-1.1.11"
    release: "spring-cloud-data-flow"
    heritage: "Helm"
  annotations:
spec:
  type: ClusterIP
  ports:
  - name: redis
    port: 6379
    targetPort: redis
  selector:
    app: spring-cloud-data-flow-redis
---
