# Source: cassandra-reaper/templates/deployment.yaml
apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: cassandra-reaper
  labels:
    app.kubernetes.io/name: cassandra-reaper
    helm.sh/chart: cassandra-reaper-0.2.3
    app.kubernetes.io/instance: cassandra-reaper
    app.kubernetes.io/managed-by: Helm
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: cassandra-reaper
      app.kubernetes.io/instance: cassandra-reaper
  template:
    metadata:
      labels:
        app.kubernetes.io/name: cassandra-reaper
        app.kubernetes.io/instance: cassandra-reaper
    spec:
      containers:
        - name: cassandra-reaper
          image: "thelastpickle/cassandra-reaper:1.3.0"
          imagePullPolicy: IfNotPresent
          env:
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
            - name: api
              containerPort: 8081
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: api
            initialDelaySeconds: 60
            periodSeconds: 20
            timeoutSeconds: 5
          readinessProbe:
            httpGet:
              path: /
              port: api
            initialDelaySeconds: 10
            periodSeconds: 10
            timeoutSeconds: 5
          resources:
            {}
